host: localhost
port: 4200

db:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: oversight

redis:
  host: localhost
  port: 6379
  to_process_queue: "PROCESS"
  under_process_queue: "UNDER_PROCESS"